spring.application.name=jwtRefreshToken-demo
server.port=8080
spring.datasource.url=jdbc:mariadb://localhost:3306/jwt_refresh_auth
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
jwt.secret=${JWT_SECRET}
jwt.expiration=864000000
jwt.refresh-expiration=894000000
jwt.issuer=jhuoi
jwt.audience=api-client
admin.username=Admin
admin.password=${ADMIN_PASSWORD}
admin.email=admin@admin.es
security.max_sessions=3
