spring.application.name=jwtRefreshToken-demo
server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/jwt_refresh_auth
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
jwt.issuer=${JWT_ISSUER:jwt.marcpericot.es}
jwt.audience=${JWT_AUDIENCE:api-client}

admin.username=Admin
admin.password=${ADMIN_PASSWORD}
admin.email=admin@admin.es

security.max_sessions=3